base_url = "https://hyperpolymath.github.io/gsbot"
title = "GSBot"
description = "GitHub Security Bot"
compile_sass = false
build_search_index = true

[markdown]
highlight_code = true

[extra]
author = "hyperpolymath"
